version: '3.8'
#######################
# Uncomment for debug #
#######################
#services:
#  golang-http:
#        security_opt:
#            - "seccomp:unconfined"
#        cap_add:
#            - SYS_PTRACE
#        ports:
#            - ${GOLANG_HTTP_SERVER_PORT_EXPOSED}:8080
#            - ${GOLANG_HTTP_DEBUG_PORT_EXPOSED}:40000
#        command:
#            - sh
#            - -c
#            - "go build -gcflags=\"all=-N -l\" -o ./debug/http-server ./cmd/http-server && dlv --listen=:40000 --headless=true --api-version=2 --accept-multiclient exec ./debug/http-server"
########################
